python3 xla_spawn.py \
  --num_cores 8 \
  train.py \
  --resume_from_checkpoint ./checkpoints/colbertv2.0 \
  --model_name_or_path bert-base-uncased \
  --config_name bert-base-uncased \
  --output_dir ./checkpoints/colbert.cqe.v0.inbatch \
  --train_file ../convir_data/canard_convir.train.triples.cqe.v0.jsonl \
  --eval_file ../convir_data/dev.triples.sample.jsonl \
  --max_q_seq_length 32 \
  --max_p_seq_length 150 \
  --colbert_type 'colbert-inbatch' \
  --dim 128 \
  --remove_unused_columns false \
  --per_device_train_batch_size 12 \ # cqe batch size
  --evaluation_strategy 'steps'\
  --learning_rate 7e-6 \ # cqe learning rate
  --max_steps 15000 \
  --save_steps 5000 \
  --eval_steps 5000 \
  --do_train \
  --do_eval
