python3 xla_spawn.py \
  --num_cores 8 \
  train.py \
  --model_name_or_path bert-base-uncased \
  --config_name bert-base-uncased \
  --output_dir ./checkpoints/samples \
  --train_file ../convir_data/canard_convir.train.triples.cqe.v0.jsonl \
  --eval_file ../convir_data/dev.triples.sample.jsonl \
  --max_q_seq_length 32 \
  --max_p_seq_length 128 \
  --colbert_type 'colbert' \
  --dim 128 \
  --remove_unused_columns false \
  --per_device_train_batch_size 4 \ # colbert's batch size
  --evaluation_strategy 'steps'\
  --learning_rate 7e-6 \ # cqe learning rate
  --max_steps 10000 \
  --save_steps 2500 \
  --eval_steps 2500 \
  --do_train \
  --do_eval
